<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="creme130" name="Reg_AccountAccess.ForgotPasswordFunctionality" tests="7" failures="0" timestamp="6 Feb 2017 13:02:31 GMT" time="73.855" errors="5">
  <testcase name="verifyAccessCredentialsPostPasswordChange" time="0.000" classname="Reg_AccountAccess.ForgotPasswordFunctionality">
    <error type="java.lang.Throwable" message="Method ForgotPasswordFunctionality.verifyAccessCredentialsPostPasswordChange()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ForgotPasswordFunctionality.verifyAccessCredentialsPostPasswordChange()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyAccessCredentialsPostPasswordChange -->
  <testcase name="verifyForgotPasswordErrorMessages" time="55.560" classname="Reg_AccountAccess.ForgotPasswordFunctionality">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 50 seconds waiting for visibility of [[FirefoxDriver: firefox on WINDOWS (dc6f3410-fc98-40c4-8c41-53839931d7e1)] -&gt; xpath: //md-content[@id=&#039;forgot-pwd-wrapper&#039;]//*[@ng-repeat=&#039;error in fieldErrors&#039;]]
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b1534ae328c771e0856c93e187490ca824&#039;, time: &#039;2016-03-15 10:43:46&#039;
System info: host: &#039;creme130&#039;, ip: &#039;192.168.17.130&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_111&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: dc6f3410-fc98-40c4-8c41-53839931d7e1">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 50 seconds waiting for visibility of [[FirefoxDriver: firefox on WINDOWS (dc6f3410-fc98-40c4-8c41-53839931d7e1)] -> xpath: //md-content[@id='forgot-pwd-wrapper']//*[@ng-repeat='error in fieldErrors']]
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'creme130', ip: '192.168.17.130', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: dc6f3410-fc98-40c4-8c41-53839931d7e1
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
	at Util.WaitTypes.waitForElementVisibilityByWebElement(WaitTypes.java:105)
	at Page.classes.LogInPage.emailNotRecognizedErrorMessageIsDisplayed(LogInPage.java:263)
	at Reg_AccountAccess.ForgotPasswordFunctionality.verifyForgotPasswordErrorMessages(ForgotPasswordFunctionality.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyForgotPasswordErrorMessages -->
  <testcase name="verifyActivationEmailReceivedAndDelete" time="0.000" classname="Reg_AccountAccess.ForgotPasswordFunctionality">
    <error type="java.lang.Throwable" message="Method ForgotPasswordFunctionality.verifyActivationEmailReceivedAndDelete()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ForgotPasswordFunctionality.verifyActivationEmailReceivedAndDelete()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyActivationEmailReceivedAndDelete -->
  <testcase name="activateUserProfileAndVerifyForgotPasswordAccepted" time="0.000" classname="Reg_AccountAccess.ForgotPasswordFunctionality">
    <error type="java.lang.Throwable" message="Method ForgotPasswordFunctionality.activateUserProfileAndVerifyForgotPasswordAccepted()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ForgotPasswordFunctionality.activateUserProfileAndVerifyForgotPasswordAccepted()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- activateUserProfileAndVerifyForgotPasswordAccepted -->
  <testcase name="verifyPageContentsAndStatus" time="8.921" classname="Reg_AccountAccess.ForgotPasswordFunctionality"/>
  <testcase name="verifyPasswordResetEmailAndChangePassword" time="0.000" classname="Reg_AccountAccess.ForgotPasswordFunctionality">
    <error type="java.lang.Throwable" message="Method ForgotPasswordFunctionality.verifyPasswordResetEmailAndChangePassword()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ForgotPasswordFunctionality.verifyPasswordResetEmailAndChangePassword()[pri:0, instance:Reg_AccountAccess.ForgotPasswordFunctionality@4bb33f74] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyPasswordResetEmailAndChangePassword -->
  <testcase name="createInactiveUserProfile" time="9.374" classname="Reg_AccountAccess.ForgotPasswordFunctionality"/>
</testsuite> <!-- Reg_AccountAccess.ForgotPasswordFunctionality -->
