<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="creme130" name="Reg_AccountAccess.LogInPageValidation" tests="7" failures="1" timestamp="6 Feb 2017 13:59:30 GMT" time="114.011" errors="3">
  <testcase name="verifyIncorrectEmailSyntaxError" time="0.000" classname="Reg_AccountAccess.LogInPageValidation">
    <error type="java.lang.Throwable" message="Method LogInPageValidation.verifyIncorrectEmailSyntaxError(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method LogInPageValidation.verifyIncorrectEmailSyntaxError(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyIncorrectEmailSyntaxError -->
  <testcase name="createActiveUserProfile" time="12.365" classname="Reg_AccountAccess.LogInPageValidation"/>
  <testcase name="pageValidationAndErrorVerification" time="63.008" classname="Reg_AccountAccess.LogInPageValidation"/>
  <testcase name="emailAuthenticationErrorMessageTest" time="18.844" classname="Reg_AccountAccess.LogInPageValidation">
    <failure type="java.lang.AssertionError" message="expected [This email has not yet been verified. A new activation link has been sent to your email address.] but found [Unable to login with provided credentials.]">
      <![CDATA[java.lang.AssertionError: expected [This email has not yet been verified. A new activation link has been sent to your email address.] but found [Unable to login with provided credentials.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Page.classes.LogInPage.verifyNonAuthenticatedLoginErrorMessage(LogInPage.java:448)
	at Reg_AccountAccess.LogInPageValidation.emailAuthenticationErrorMessageTest(LogInPageValidation.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- emailAuthenticationErrorMessageTest -->
  <testcase name="verifyCaseVariationsOfEmailAddressesAreAccepted" time="0.000" classname="Reg_AccountAccess.LogInPageValidation">
    <error type="java.lang.Throwable" message="Method LogInPageValidation.verifyCaseVariationsOfEmailAddressesAreAccepted(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method LogInPageValidation.verifyCaseVariationsOfEmailAddressesAreAccepted(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyCaseVariationsOfEmailAddressesAreAccepted -->
  <testcase name="logOut" time="19.794" classname="Reg_AccountAccess.LogInPageValidation"/>
  <testcase name="verifyVariationsOfValidCaseSensitivePasswordsAreNotAccepted" time="0.000" classname="Reg_AccountAccess.LogInPageValidation">
    <error type="java.lang.Throwable" message="Method LogInPageValidation.verifyVariationsOfValidCaseSensitivePasswordsAreNotAccepted(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method LogInPageValidation.verifyVariationsOfValidCaseSensitivePasswordsAreNotAccepted(java.lang.String)[pri:0, instance:Reg_AccountAccess.LogInPageValidation@10163d6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyVariationsOfValidCaseSensitivePasswordsAreNotAccepted -->
</testsuite> <!-- Reg_AccountAccess.LogInPageValidation -->
